### ISSUE TITLE
ca.pem: no such file or directory

### ISSUE THREAD

**Issue by stevezau** [wearemolecule/route53-kubernetes#15]
Hi, 

Following the setup instructions i seem to be stuck with 

```
2016-08-29T11:21:23.334391202Z I0829 11:21:23.334221       1 service_listener.go:28] Route53 Update Service
2016-08-29T11:21:23.334509248Z F0829 11:21:23.334311       1 service_listener.go:54] Couldn't set up tls transport: open /etc/kubernetes/ssl/ca.pem: no such file or directory
```

Where do i get the cert files from? What are they meant to be for? They don't exist on my master or minion servers?

**Comment by stevezau** [comment]
I've been pulling my hair out trying to find these files.. 

I've deployed kube following: http://kubernetes.io/docs/getting-started-guides/aws/ using kube-up.sh.

I've looked everything and can't find where the certs are stored? Please help :D

**Comment by stevezau** [comment]
Ok finally managed to figure this out..

Two things the ca already exists within /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

the cert and key i found within ~/.kube/config where i manually created a secret..

such as

```
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: ssl-cert
type: Opaque
data:
  cert: <insert client-certificate-data from config>
  key: <insert client-key-data from config>
```

my rc now is

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: route53-kubernetes
  namespace: kube-system
  labels:
    app: route53-kubernetes
spec:
  replicas: 1
  selector:
    app: route53-kubernetes
  template:
    metadata:
      labels:
        app: route53-kubernetes
    spec:
      volumes:
        - name: ssl-cert
          secret:
            secretName: "ssl-cert"
      containers:
        - image: quay.io/molecule/route53-kubernetes:v1.1.4
          imagePullPolicy: Always
          name: route53-kubernetes
          volumeMounts:
            - name: ssl-cert
              mountPath: /ssl
              readOnly: true
          env:
            - name: "CA_FILE_PATH"
              value: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
            - name: "CERT_FILE_PATH"
              value: "/ssl/cert"
            - name: "KEY_FILE_PATH"
              value: "/ssl/key"
            - name : "AWS_REGION"
              value: "us-east-1"
```
