### ISSUE TITLE
kubernetes documentation

### ISSUE THREAD

**Issue by Moggy-the-Man** [wearemolecule/route53-kubernetes#3]
Any chance we could get documentation regarding how to run the route53-kubernetes rc/service? on kubernetes, perhaps a .yml file? thanks

**Comment by iterion** [comment]
Hello,

We currently use this rc.yaml

``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: route53-kubernetes
  name: route53-kubernetes
  namespace: molecule-cluster-utils
spec:
  replicas: 1
  selector:
    app: route53-kubernetes
  template:
    metadata:
      labels:
        app: route53-kubernetes
    spec:
      containers:
      - env:
        - name: CA_FILE_PATH
          value: /opt/certs/ca.pem
        - name: CERT_FILE_PATH
          value: /opt/certs/cert.pem
        - name: KEY_FILE_PATH
          value: /opt/certs/key.pem
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /opt/creds/credentials
        image: quay.io/molecule/route53-kubernetes:v1.1.1
        name: route53-kubernetes
        volumeMounts:
        - mountPath: /opt/certs
          name: ssl-cert
          readOnly: true
        - mountPath: /opt/creds
          name: aws-creds
          readOnly: true
      volumes:
      - name: ssl-cert
        secret:
          secretName: kube-ssl
      - name: aws-creds
        secret:
          secretName: aws-creds
```

I'll go ahead and add this to the repo for future reference as well. No service is necessary as nothing is connecting directly to these pods.

The above assumes that you connect to your cluster with ssl certs (given by the secret `kube-ssl`) and that you have an IAM role set up on AWS and defined in the secret `aws-creds`.

We'd be happy to support other cluster setups, just send us a PR.
